"""CGA translation embedding, the conformal counterpart of GATr's `embed_translation`.

GGTF's model encodes a drift hit as a point plus a translation:

    embed_point(position) + embed_scalar(hit_type) + embed_translation(vector)

so the pair says "the hit is here, and the other solution of the left/right
ambiguity is this vector away". Reproducing that in the conformal algebra needs a
translation object, which is what this module provides.

In CGA a translation is not a vector offset, it is a rotor generated by the point at
infinity:

    T(t) = exp(-t n_inf / 2) = 1 - (t ^ n_inf) / 2

because `t ^ n_inf` squares to zero, so the exponential terminates after one term.
The projective case (Dorst, PGA4CS Eq. 82) has the same shape with `e_0` in place of
`n_inf`; the algebras differ in which null direction generates the translation, and
picking the wrong one is exactly the bug documented in
`paper_adjustment_candidates/drift_embedding_null_vector.md`. Here `n_inf` is fixed
by the point embedding in `point.py`: writing that point as

    P = x + (r^2 / 2)(e- - e+) + (e+ + e-) / 2

identifies `n_inf = e- - e+` and `n_0 = (e+ + e-) / 2`, which satisfy the
`n_inf . n_0 = -1` normalisation this algebra needs. Using `n_0` instead would leave
a `T` that does not commute with the metric correctly and translates nothing.

A note on why this exists at all, since CGA has a better option. A drift circle can be
embedded *directly* as a conformal circle or sphere, which is strictly more expressive
than a point plus an offset -- that is what `circle.py` and `sphere.py` do and what our
own conformal arm uses. This module is deliberately the poorer encoding: it exists so
the algebra can be swapped inside GGTF's model with their encoding held fixed, which
is the only way to read the resulting comparison as being about the algebra. See
`models/Cgatr_withModifications.py`.

Grade-2 indices in the ordering fixed by `generate_cga_tables.py`, where `e4` is `e+`
and `e5` is `e-`:
     8: e1 e+     9: e1 e-
    11: e2 e+    12: e2 e-
    13: e3 e+    14: e3 e-
"""

import torch

# (e_i ^ e+, e_i ^ e-) for i = x, y, z.
_PLUS_IDX = (8, 11, 13)
_MINUS_IDX = (9, 12, 14)


def embed_translation(translation_vector: torch.Tensor) -> torch.Tensor:
    """Embeds a 3D translation as a CGA translator.

    Expanding `T(t) = 1 - (t ^ n_inf) / 2` with `n_inf = e- - e+` gives

        T(t) = 1 - (1/2) sum_i t_i (e_i e- - e_i e+)

    so each component contributes `+t_i / 2` on `e_i e+` and `-t_i / 2` on `e_i e-`.

    Parameters
    ----------
    translation_vector : torch.Tensor with shape (..., 3)
        Vectorial amount of translation.

    Returns
    -------
    multivector : torch.Tensor with shape (..., 32)
        Embedding into multivector.
    """
    batch_shape = translation_vector.shape[:-1]
    mv = torch.zeros(
        *batch_shape, 32,
        dtype=translation_vector.dtype, device=translation_vector.device,
    )

    mv[..., 0] = 1.0
    for axis, (plus, minus) in enumerate(zip(_PLUS_IDX, _MINUS_IDX)):
        half = 0.5 * translation_vector[..., axis]
        mv[..., plus] = half
        mv[..., minus] = -half

    return mv


def extract_translation(multivector: torch.Tensor) -> torch.Tensor:
    """Reads the translation back out of a translator.

    The inverse of `embed_translation` up to the scalar part, which a translator
    carries as 1 and which this ignores. Provided for tests and for inspecting a
    learned multivector, not used on the forward path.

    Parameters
    ----------
    multivector : torch.Tensor with shape (..., 32)

    Returns
    -------
    translation_vector : torch.Tensor with shape (..., 3)
    """
    # Averaging the two halves rather than reading one is deliberate: on a multivector
    # that is not exactly a translator the two disagree, and the average is the least
    # arbitrary reading of it.
    plus = torch.stack([multivector[..., i] for i in _PLUS_IDX], dim=-1)
    minus = torch.stack([multivector[..., i] for i in _MINUS_IDX], dim=-1)
    return plus - minus
